using System.Text.Json;
using ContactConnection.Application.Interfaces.Services;
using ContactConnection.Application.Services;
using ContactConnection.Domain.Entities;
using ContactConnection.Domain.ValueObjects.Exports;
using ContactConnection.Infrastructure.Data;
using ContactConnection.Infrastructure.Exports;
using Microsoft.EntityFrameworkCore;

namespace ContactConnection.Api.Endpoints;

/// <summary>
/// Export Worker (S180, Sprint 2 item 2): export definitions, their vendor lifecycle (draft → testing → approved → live),
/// Preview, test files and Run now, run history and downloads. Files are generated by the Worker's ExportRunService from
/// the queue; Preview renders a few calls right here. Everything sits behind reports.manage — export files carry
/// customer details (never card data).
/// </summary>
public static class ExportsEndpoints
{
    private const int DefaultPreviewCalls = 25;
    private const int MaxPreviewCalls = 200;
    private const int MaxPreviewChars = 200_000;

    public static IEndpointRouteBuilder MapExportsEndpoints(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/api/v1/exports").RequireAuthorization("ReportsManage");
        g.MapGet("", List);
        g.MapPost("", Create);
        g.MapPost("preview", Preview);
        g.MapGet("{id:guid}", Get);
        g.MapPut("{id:guid}", Update);
        g.MapDelete("{id:guid}", Delete);
        g.MapGet("{id:guid}/versions", Versions);
        g.MapPost("{id:guid}/lifecycle", Lifecycle);
        g.MapGet("{id:guid}/runs", Runs);
        g.MapPost("{id:guid}/runs", QueueRun);

        var r = app.MapGroup("/api/v1/export-runs").RequireAuthorization("ReportsManage");
        r.MapGet("{runId:guid}/download", Download);
        r.MapPost("{runId:guid}/rerun", Rerun);
        return app;
    }

    // ── Definitions ────────────────────────────────────────────────────────────

    private static async Task<IResult> List(ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var defs = await db.ExportDefinitions.AsNoTracking().OrderBy(d => d.Name).ToListAsync(ct);
        var ids = defs.Select(d => d.Id).ToList();
        var lastRuns = (await db.ExportRuns.AsNoTracking().Where(x => ids.Contains(x.DefinitionId))
                .GroupBy(x => x.DefinitionId)
                .Select(grp => grp.OrderByDescending(x => x.QueuedAt).First())
                .ToListAsync(ct))
            .ToDictionary(x => x.DefinitionId);
        return Results.Ok(defs.Select(d => ToResponse(d, lastRuns.GetValueOrDefault(d.Id))));
    }

    private static async Task<IResult> Get(Guid id, ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct);
        return d is null ? Results.NotFound() : Results.Ok(ToResponse(d, null));
    }

    private static async Task<IResult> Create(
        SaveExportRequest req, ScopedTenantDbContextFactory dbf, IExportGenerator generator,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        if (string.IsNullOrWhiteSpace(req.Name)) return Results.BadRequest(new { error = "A name is required." });
        var spec = WithDefaults(req.Spec ?? new ExportSpec(), tenant.Timezone);
        if (generator.Validate(spec) is { } error) return Results.BadRequest(new { error });

        await using var db = dbf.Create();
        var d = ExportDefinition.Create(tenant.Id, req.Name, req.Description, spec);
        db.ExportDefinitions.Add(d);
        await db.SaveChangesAsync(ct);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, "Created", ct);
        return Results.Created($"/api/v1/exports/{d.Id}", ToResponse(d, null));
    }

    private static async Task<IResult> Update(
        Guid id, SaveExportRequest req, ScopedTenantDbContextFactory dbf, IExportGenerator generator,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        if (string.IsNullOrWhiteSpace(req.Name)) return Results.BadRequest(new { error = "A name is required." });
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();

        var spec = WithDefaults(req.Spec ?? d.Spec, tenant.Timezone);
        if (generator.Validate(spec) is { } error) return Results.BadRequest(new { error });
        var renamed = d.Name != req.Name.Trim() || d.Description != (string.IsNullOrWhiteSpace(req.Description) ? null : req.Description.Trim());
        d.Rename(req.Name, req.Description);
        var specChanged = d.UpdateSpec(spec);
        await db.SaveChangesAsync(ct);
        if (renamed || specChanged)
        {
            var summary = specChanged
                ? d.ChangedSinceApproval ? $"Layout/data changed (revision {d.SpecRevision}) — differs from the vendor-approved revision {d.ApprovedSpecRevision}" : $"Layout/data changed (revision {d.SpecRevision})"
                : "Renamed";
            await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, summary, ct);
        }
        return Results.Ok(ToResponse(d, null));
    }

    /// <summary>Only a draft can be deleted (an approved or live export is a vendor commitment — pause it instead).</summary>
    private static async Task<IResult> Delete(
        Guid id, ScopedTenantDbContextFactory dbf, IBlobStorage blobs, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        if (d.Status != ExportStatus.Draft)
            return Results.Conflict(new { error = "Only a draft export can be deleted — move it back to draft first." });
        if (await db.ExportRuns.AnyAsync(x => x.DefinitionId == id && (x.Status == ExportRunStatus.Queued || x.Status == ExportRunStatus.Running), ct))
            return Results.Conflict(new { error = "A file is being generated — try again when it finishes." });
        db.ExportRuns.RemoveRange(db.ExportRuns.Where(x => x.DefinitionId == id));
        db.ExportDefinitions.Remove(d);
        await db.SaveChangesAsync(ct);
        await blobs.DeletePrefixAsync($"exports/{id}/", ct);
        return Results.NoContent();
    }

    private static async Task<IResult> Versions(
        Guid id, [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        return Results.Ok(await versions.ListVersionsAsync(VersionedEntityType.ExportDefinition, id, ct));
    }

    private static async Task<IResult> Lifecycle(
        Guid id, LifecycleRequest req, ScopedTenantDbContextFactory dbf,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();

        string summary;
        try
        {
            switch (req.Action)
            {
                case "start_testing":
                    d.StartTesting(); summary = "Moved to testing"; break;
                case "approve":
                    if (string.IsNullOrWhiteSpace(req.VendorContact))
                        return Results.BadRequest(new { error = "Who at the vendor approved it?" });
                    if (req.RunId is not { } runId) return Results.BadRequest(new { error = "Choose the test file the vendor approved." });
                    var run = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId && x.DefinitionId == id, ct);
                    if (run is not { IsTest: true, Status: ExportRunStatus.Succeeded })
                        return Results.BadRequest(new { error = "That isn't a finished test file of this export." });
                    d.Approve(req.VendorContact, actor.Name, req.Note, runId);
                    summary = $"Vendor approval recorded — {req.VendorContact.Trim()} approved test file {run.FileName}"
                              + (run.SpecRevision != d.SpecRevision ? $" (made from revision {run.SpecRevision}; current is {d.SpecRevision})" : "")
                              + (string.IsNullOrWhiteSpace(req.Note) ? "" : $": {req.Note.Trim()}");
                    break;
                case "go_live":
                    d.GoLive(); summary = "Went live"; break;
                case "pause":
                    d.Pause(); summary = "Paused"; break;
                case "back_to_draft":
                    d.BackToDraft(); summary = "Moved back to draft"; break;
                default:
                    return Results.BadRequest(new { error = $"Unknown action '{req.Action}'." });
            }
        }
        catch (InvalidOperationException ex) { return Results.Conflict(new { error = ex.Message }); }

        await db.SaveChangesAsync(ct);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, summary, ct);
        return Results.Ok(ToResponse(d, null));
    }

    // ── Preview ────────────────────────────────────────────────────────────────

    /// <summary>Renders the (possibly unsaved) spec against real calls in the window — capped, nothing stored.
    /// An xlsx layout previews as tab-separated text so the grid can show it.</summary>
    private static async Task<IResult> Preview(
        PreviewRequest req, IExportGenerator generator, TenantContext tc, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        var spec = WithDefaults(req.Spec, tenant.Timezone);
        if (generator.Validate(spec) is { } invalid) return Results.Ok(new PreviewResponse(false, invalid, 0, 0, false, "", "", false));
        if (!TryWindow(req.From, req.To, spec.TimeZone, out var start, out var end, out var werr)) return Results.BadRequest(new { error = werr });
        var source = req.DataSource ?? ExportDataSource.Production;
        if (!ExportDataSource.IsValid(source)) return Results.BadRequest(new { error = "Data source must be production or practice." });

        var asGrid = spec.LayoutMode == ExportLayoutMode.Columns && spec.Format == ExportFormat.Xlsx;
        var renderSpec = asGrid
            ? spec with { Format = ExportFormat.Delimited, Delimiter = "\t", LineEnding = "lf", Columns = spec.Columns.Select(c => c with { Quote = "never" }).ToList() }
            : spec;
        var request = new ExportGenerationRequest(renderSpec, req.Name ?? "Preview", null, req.IsTest, source, start, end,
            Math.Clamp(req.MaxCalls ?? DefaultPreviewCalls, 1, MaxPreviewCalls));
        using var ms = new MemoryStream();
        var result = await generator.GenerateAsync(request, ms, ct);
        var text = ExportRowWriter.Utf8NoBom.GetString(ms.GetBuffer(), 0, (int)Math.Min(ms.Length, MaxPreviewChars * 4));
        if (text.Length > MaxPreviewChars) text = text[..MaxPreviewChars];
        var fileName = generator.RenderFileName(request with { Spec = spec });
        return Results.Ok(new PreviewResponse(result.Success, result.Error, result.RowCount, result.CallCount, result.Truncated,
            text, fileName, asGrid));
    }

    // ── Runs ───────────────────────────────────────────────────────────────────

    private static async Task<IResult> Runs(Guid id, int? limit, ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var runs = await db.ExportRuns.AsNoTracking().Where(x => x.DefinitionId == id)
            .OrderByDescending(x => x.QueuedAt).Take(Math.Clamp(limit ?? 50, 1, 500)).ToListAsync(ct);
        return Results.Ok(runs.Select(RunResponse));
    }

    /// <summary>Run now / Generate test file for a date range (dates in the export's time zone, both inclusive).</summary>
    private static async Task<IResult> QueueRun(
        Guid id, QueueRunRequest req, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        var actor = ActorResolver.Resolve(http.User);
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        if (!TryWindow(req.From, req.To, d.Spec.TimeZone, out var start, out var end, out var werr)) return Results.BadRequest(new { error = werr });
        var source = req.DataSource ?? ExportDataSource.Production;
        if (!ExportDataSource.IsValid(source)) return Results.BadRequest(new { error = "Data source must be production or practice." });
        if (source == ExportDataSource.Practice && !req.IsTest)
            return Results.BadRequest(new { error = "Practice calls can only go into a test file." });

        var run = ExportRun.Queue(d, req.IsTest ? ExportRunKind.Test : ExportRunKind.Manual, req.IsTest, source, start, end,
            actor?.Id, actor?.Name);
        db.ExportRuns.Add(run);
        await db.SaveChangesAsync(ct);
        return Results.Accepted($"/api/v1/exports/{id}/runs", RunResponse(run));
    }

    /// <summary>Generate a past run's window again with today's data and the export's current layout (agencies send late
    /// changes). A test run re-runs as a test.</summary>
    private static async Task<IResult> Rerun(Guid runId, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        var actor = ActorResolver.Resolve(http.User);
        await using var db = dbf.Create();
        var old = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId, ct);
        if (old is null) return Results.NotFound();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == old.DefinitionId, ct);
        if (d is null) return Results.NotFound();
        var run = ExportRun.Queue(d, old.IsTest ? ExportRunKind.Test : ExportRunKind.Rerun, old.IsTest, old.DataSource,
            old.WindowStart, old.WindowEnd, actor?.Id, actor?.Name);
        db.ExportRuns.Add(run);
        await db.SaveChangesAsync(ct);
        return Results.Accepted($"/api/v1/exports/{d.Id}/runs", RunResponse(run));
    }

    private static async Task<IResult> Download(
        Guid runId, ScopedTenantDbContextFactory dbf, IBlobStorage blobs, TenantContext tc, HttpContext http,
        ILoggerFactory loggers, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var run = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId, ct);
        if (run is not { Status: ExportRunStatus.Succeeded, BlobKey: { } key }) return Results.NotFound();
        var stream = await blobs.OpenReadAsync(key, ct);
        if (stream is null) return Results.NotFound(new { error = "The file is no longer stored." });
        var actor = ActorResolver.Resolve(http.User);
        loggers.CreateLogger("ContactConnection.Exports").LogInformation(
            "Export file downloaded: run {RunId} ({File}, {Name}) by {Actor}", run.Id, run.FileName, run.DefinitionName, actor?.Name ?? "unknown");
        return Results.File(stream, run.ContentType ?? "application/octet-stream", run.FileName);
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private static ExportSpec WithDefaults(ExportSpec spec, string? tenantTimezone) =>
        string.IsNullOrWhiteSpace(spec.TimeZone)
            ? spec with { TimeZone = string.IsNullOrWhiteSpace(tenantTimezone) ? "America/New_York" : tenantTimezone }
            : spec;

    /// <summary>[from 00:00, to + 1 day 00:00) in the export's time zone, as UTC.</summary>
    internal static bool TryWindow(DateOnly? from, DateOnly? to, string tz, out DateTimeOffset start, out DateTimeOffset end, out string? error)
    {
        start = end = default;
        error = null;
        if (from is null || to is null) { error = "Choose the dates to include."; return false; }
        if (to < from) { error = "The end date is before the start date."; return false; }
        if (to.Value.DayNumber - from.Value.DayNumber > 366) { error = "Choose at most a year."; return false; }
        var zone = ExportGenerator.ResolveZone(tz) ?? TimeZoneInfo.Utc;
        start = LocalMidnight(from.Value, zone);
        end = LocalMidnight(to.Value.AddDays(1), zone);
        return true;
    }

    private static DateTimeOffset LocalMidnight(DateOnly day, TimeZoneInfo zone)
    {
        var local = day.ToDateTime(TimeOnly.MinValue);
        return new DateTimeOffset(local, zone.GetUtcOffset(local)).ToUniversalTime();
    }

    private static string Snapshot(ExportDefinition d) => JsonSerializer.Serialize(new
    {
        d.Name, d.Description, d.Status, d.SpecRevision, d.Spec,
        Approval = d.ApprovedAt is null ? null : new { d.ApprovedAt, d.ApprovedByVendorContact, d.ApprovalRecordedByName, d.ApprovalNote, d.ApprovedRunId, d.ApprovedSpecRevision },
    }, new JsonSerializerOptions(JsonSerializerDefaults.Web));

    private static object ToResponse(ExportDefinition d, ExportRun? lastRun) => new
    {
        d.Id, d.Name, d.Description, d.Status, d.Spec, d.SpecRevision, d.ChangedSinceApproval,
        Approval = d.ApprovedAt is null ? null : new
        {
            At = d.ApprovedAt, VendorContact = d.ApprovedByVendorContact, RecordedBy = d.ApprovalRecordedByName,
            Note = d.ApprovalNote, RunId = d.ApprovedRunId, SpecRevision = d.ApprovedSpecRevision,
        },
        d.CreatedAt, d.UpdatedAt,
        LastRun = lastRun is null ? null : RunResponse(lastRun),
    };

    private static object RunResponse(ExportRun r) => new
    {
        r.Id, r.DefinitionId, r.DefinitionName, r.SpecRevision, r.Kind, r.IsTest, r.DataSource, r.WindowStart, r.WindowEnd,
        r.Status, r.Attempts, r.Error, r.RequestedByName, r.RowCount, r.CallCount, r.FileName, r.FileSize, r.Sha256,
        r.QueuedAt, r.StartedAt, r.FinishedAt,
    };

    public sealed record SaveExportRequest(string Name, string? Description, ExportSpec? Spec);
    public sealed record LifecycleRequest(string Action, string? VendorContact, string? Note, Guid? RunId);
    public sealed record PreviewRequest(ExportSpec Spec, string? Name, DateOnly? From, DateOnly? To, string? DataSource, bool IsTest, int? MaxCalls);
    public sealed record PreviewResponse(bool Success, string? Error, int RowCount, int CallCount, bool Truncated, string Text, string FileName, bool Grid);
    public sealed record QueueRunRequest(DateOnly? From, DateOnly? To, bool IsTest, string? DataSource);
}
