using System.Text.Json;
using ContactConnection.Application.Interfaces.Services;
using ContactConnection.Application.Services;
using ContactConnection.Domain.Entities;
using ContactConnection.Domain.ValueObjects.Exports;
using ContactConnection.Infrastructure.Data;
using ContactConnection.Infrastructure.Exports;
using Microsoft.EntityFrameworkCore;

namespace ContactConnection.Api.Endpoints;

/// <summary>
/// Export Worker (S180, Sprint 2 item 2): export definitions, their vendor lifecycle (draft → testing → approved → live),
/// Preview, test files and Run now, run history and downloads. Files are generated by the Worker's ExportRunService from
/// the queue; Preview renders a few calls right here. Everything sits behind reports.manage — export files carry
/// customer details (never card data).
/// </summary>
public static class ExportsEndpoints
{
    private const int DefaultPreviewCalls = 25;
    private const int MaxPreviewCalls = 200;
    private const int MaxPreviewChars = 200_000;

    public static IEndpointRouteBuilder MapExportsEndpoints(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/api/v1/exports").RequireAuthorization("ReportsManage");
        g.MapGet("", List);
        g.MapPost("", Create);
        g.MapPost("preview", Preview);
        g.MapGet("{id:guid}", Get);
        g.MapPut("{id:guid}", Update);
        g.MapDelete("{id:guid}", Delete);
        g.MapGet("{id:guid}/versions", Versions);
        g.MapPost("{id:guid}/lifecycle", Lifecycle);
        g.MapGet("{id:guid}/runs", Runs);
        g.MapPost("{id:guid}/runs", QueueRun);
        g.MapGet("templates", Templates);
        g.MapPut("{id:guid}/schedule", SaveSchedule);
        g.MapPost("schedule-preview", SchedulePreview);
        g.MapPut("{id:guid}/delivery-targets", SaveTargets);
        g.MapPost("{id:guid}/delivery-targets/test", TestTarget);
        g.MapGet("{id:guid}/activity", Activity);

        var r = app.MapGroup("/api/v1/export-runs").RequireAuthorization("ReportsManage");
        r.MapGet("{runId:guid}/download", Download);
        r.MapPost("{runId:guid}/rerun", Rerun);
        r.MapPost("{runId:guid}/send", Send);

        app.MapPost("/api/v1/export-deliveries/{deliveryId:guid}/retry", RetryDelivery).RequireAuthorization("ReportsManage");
        return app;
    }

    // ── Definitions ────────────────────────────────────────────────────────────

    private static async Task<IResult> List(ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var defs = await db.ExportDefinitions.AsNoTracking().OrderBy(d => d.Name).ToListAsync(ct);
        var ids = defs.Select(d => d.Id).ToList();
        var lastRuns = (await db.ExportRuns.AsNoTracking().Where(x => ids.Contains(x.DefinitionId))
                .GroupBy(x => x.DefinitionId)
                .Select(grp => grp.OrderByDescending(x => x.QueuedAt).First())
                .ToListAsync(ct))
            .ToDictionary(x => x.DefinitionId);
        return Results.Ok(defs.Select(d => ToResponse(d, lastRuns.GetValueOrDefault(d.Id))));
    }

    private static async Task<IResult> Get(Guid id, ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct);
        return d is null ? Results.NotFound() : Results.Ok(ToResponse(d, null));
    }

    private static async Task<IResult> Create(
        SaveExportRequest req, ScopedTenantDbContextFactory dbf, IExportGenerator generator,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        if (string.IsNullOrWhiteSpace(req.Name)) return Results.BadRequest(new { error = "A name is required." });
        var spec = WithDefaults(req.Spec ?? new ExportSpec(), tenant.Timezone);
        if (generator.Validate(spec) is { } error) return Results.BadRequest(new { error });

        await using var db = dbf.Create();
        var d = ExportDefinition.Create(tenant.Id, req.Name, req.Description, spec);
        db.ExportDefinitions.Add(d);
        await db.SaveChangesAsync(ct);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, "Created", ct);
        return Results.Created($"/api/v1/exports/{d.Id}", ToResponse(d, null));
    }

    private static async Task<IResult> Update(
        Guid id, SaveExportRequest req, ScopedTenantDbContextFactory dbf, IExportGenerator generator,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        if (string.IsNullOrWhiteSpace(req.Name)) return Results.BadRequest(new { error = "A name is required." });
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();

        var spec = WithDefaults(req.Spec ?? d.Spec, tenant.Timezone);
        if (generator.Validate(spec) is { } error) return Results.BadRequest(new { error });
        var renamed = d.Name != req.Name.Trim() || d.Description != (string.IsNullOrWhiteSpace(req.Description) ? null : req.Description.Trim());
        d.Rename(req.Name, req.Description);
        var specChanged = d.UpdateSpec(spec);
        await db.SaveChangesAsync(ct);
        if (renamed || specChanged)
        {
            var summary = specChanged
                ? d.ChangedSinceApproval ? $"Layout/data changed (revision {d.SpecRevision}) — differs from the vendor-approved revision {d.ApprovedSpecRevision}" : $"Layout/data changed (revision {d.SpecRevision})"
                : "Renamed";
            await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, summary, ct);
        }
        return Results.Ok(ToResponse(d, null));
    }

    /// <summary>Only a draft can be deleted (an approved or live export is a vendor commitment — pause it instead).</summary>
    private static async Task<IResult> Delete(
        Guid id, ScopedTenantDbContextFactory dbf, IBlobStorage blobs, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        if (d.Status != ExportStatus.Draft)
            return Results.Conflict(new { error = "Only a draft export can be deleted — move it back to draft first." });
        if (await db.ExportRuns.AnyAsync(x => x.DefinitionId == id && (x.Status == ExportRunStatus.Queued || x.Status == ExportRunStatus.Running), ct))
            return Results.Conflict(new { error = "A file is being generated — try again when it finishes." });
        if (await db.ExportDeliveries.AnyAsync(x => x.DefinitionId == id && (x.Status == ExportDeliveryStatus.Queued || x.Status == ExportDeliveryStatus.Running), ct))
            return Results.Conflict(new { error = "A file is still being sent — try again when it finishes." });
        db.ExportDeliveries.RemoveRange(db.ExportDeliveries.Where(x => x.DefinitionId == id));
        db.ExportAuditEntries.RemoveRange(db.ExportAuditEntries.Where(x => x.DefinitionId == id));
        db.ExportRuns.RemoveRange(db.ExportRuns.Where(x => x.DefinitionId == id));
        db.ExportDefinitions.Remove(d);
        await db.SaveChangesAsync(ct);
        await blobs.DeletePrefixAsync($"exports/{id}/", ct);
        return Results.NoContent();
    }

    private static async Task<IResult> Versions(
        Guid id, [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        return Results.Ok(await versions.ListVersionsAsync(VersionedEntityType.ExportDefinition, id, ct));
    }

    private static async Task<IResult> Lifecycle(
        Guid id, LifecycleRequest req, ScopedTenantDbContextFactory dbf,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();

        string summary;
        try
        {
            switch (req.Action)
            {
                case "start_testing":
                    d.StartTesting(); summary = "Moved to testing"; break;
                case "approve":
                    if (string.IsNullOrWhiteSpace(req.VendorContact))
                        return Results.BadRequest(new { error = "Who at the vendor approved it?" });
                    if (req.RunId is not { } runId) return Results.BadRequest(new { error = "Choose the test file the vendor approved." });
                    var run = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId && x.DefinitionId == id, ct);
                    if (run is not { IsTest: true, Status: ExportRunStatus.Succeeded })
                        return Results.BadRequest(new { error = "That isn't a finished test file of this export." });
                    d.Approve(req.VendorContact, actor.Name, req.Note, runId);
                    summary = $"Vendor approval recorded — {req.VendorContact.Trim()} approved test file {run.FileName}"
                              + (run.SpecRevision != d.SpecRevision ? $" (made from revision {run.SpecRevision}; current is {d.SpecRevision})" : "")
                              + (string.IsNullOrWhiteSpace(req.Note) ? "" : $": {req.Note.Trim()}");
                    break;
                case "go_live":
                    d.GoLive(); summary = "Went live"; break;
                case "pause":
                    d.Pause(); summary = "Paused"; break;
                case "back_to_draft":
                    d.BackToDraft(); summary = "Moved back to draft"; break;
                default:
                    return Results.BadRequest(new { error = $"Unknown action '{req.Action}'." });
            }
        }
        catch (InvalidOperationException ex) { return Results.Conflict(new { error = ex.Message }); }

        await db.SaveChangesAsync(ct);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, summary, ct);
        return Results.Ok(ToResponse(d, null));
    }

    // ── Preview ────────────────────────────────────────────────────────────────

    /// <summary>Renders the (possibly unsaved) spec against real calls in the window — capped, nothing stored.
    /// An xlsx layout previews as tab-separated text so the grid can show it.</summary>
    private static async Task<IResult> Preview(
        PreviewRequest req, IExportGenerator generator, TenantContext tc, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        var spec = WithDefaults(req.Spec, tenant.Timezone);
        if (generator.Validate(spec) is { } invalid) return Results.Ok(new PreviewResponse(false, invalid, 0, 0, false, "", "", false));
        if (!TryWindow(req.From, req.To, spec.TimeZone, out var start, out var end, out var werr)) return Results.BadRequest(new { error = werr });
        var source = req.DataSource ?? ExportDataSource.Production;
        if (!ExportDataSource.IsValid(source)) return Results.BadRequest(new { error = "Data source must be production or practice." });

        var asGrid = spec.LayoutMode == ExportLayoutMode.Columns && spec.Format == ExportFormat.Xlsx;
        var renderSpec = asGrid
            ? spec with { Format = ExportFormat.Delimited, Delimiter = "\t", LineEnding = "lf", Columns = spec.Columns.Select(c => c with { Quote = "never" }).ToList() }
            : spec;
        var request = new ExportGenerationRequest(renderSpec, req.Name ?? "Preview", null, req.IsTest, source, start, end,
            Math.Clamp(req.MaxCalls ?? DefaultPreviewCalls, 1, MaxPreviewCalls));
        using var ms = new MemoryStream();
        var result = await generator.GenerateAsync(request, ms, ct);
        var text = ExportRowWriter.Utf8NoBom.GetString(ms.GetBuffer(), 0, (int)Math.Min(ms.Length, MaxPreviewChars * 4));
        if (text.Length > MaxPreviewChars) text = text[..MaxPreviewChars];
        var fileName = generator.RenderFileName(request with { Spec = spec });
        return Results.Ok(new PreviewResponse(result.Success, result.Error, result.RowCount, result.CallCount, result.Truncated,
            text, fileName, asGrid));
    }

    // ── Runs ───────────────────────────────────────────────────────────────────

    private static async Task<IResult> Runs(Guid id, int? limit, ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var runs = await db.ExportRuns.AsNoTracking().Where(x => x.DefinitionId == id)
            .OrderByDescending(x => x.QueuedAt).Take(Math.Clamp(limit ?? 50, 1, 500)).ToListAsync(ct);
        var runIds = runs.Select(x => x.Id).ToList();
        var deliveries = (await db.ExportDeliveries.AsNoTracking().Where(x => runIds.Contains(x.RunId)).OrderBy(x => x.QueuedAt).ToListAsync(ct))
            .ToLookup(x => x.RunId);
        return Results.Ok(runs.Select(x => RunResponse(x, deliveries[x.Id])));
    }

    /// <summary>Run now / Generate test file for a date range (dates in the export's time zone, both inclusive).</summary>
    private static async Task<IResult> QueueRun(
        Guid id, QueueRunRequest req, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        var actor = ActorResolver.Resolve(http.User);
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        if (!TryWindow(req.From, req.To, d.Spec.TimeZone, out var start, out var end, out var werr)) return Results.BadRequest(new { error = werr });
        var source = req.DataSource ?? ExportDataSource.Production;
        if (!ExportDataSource.IsValid(source)) return Results.BadRequest(new { error = "Data source must be production or practice." });
        if (source == ExportDataSource.Practice && !req.IsTest)
            return Results.BadRequest(new { error = "Practice calls can only go into a test file." });

        if (req.Deliver && !req.IsTest && SendBlocked(d) is { } blocked) return Results.Conflict(new { error = blocked });
        var run = ExportRun.Queue(d, req.IsTest ? ExportRunKind.Test : ExportRunKind.Manual, req.IsTest, source, start, end,
            actor?.Id, actor?.Name, deliver: req.Deliver && !req.IsTest);
        db.ExportRuns.Add(run);
        await db.SaveChangesAsync(ct);
        return Results.Accepted($"/api/v1/exports/{id}/runs", RunResponse(run));
    }

    /// <summary>Generate a past run's window again with today's data and the export's current layout (agencies send late
    /// changes). A test run re-runs as a test.</summary>
    private static async Task<IResult> Rerun(Guid runId, RerunRequest? req, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        var actor = ActorResolver.Resolve(http.User);
        await using var db = dbf.Create();
        var old = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId, ct);
        if (old is null) return Results.NotFound();
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == old.DefinitionId, ct);
        if (d is null) return Results.NotFound();
        var deliver = req?.Deliver == true && !old.IsTest;
        if (deliver && SendBlocked(d) is { } blocked) return Results.Conflict(new { error = blocked });
        var run = ExportRun.Queue(d, old.IsTest ? ExportRunKind.Test : ExportRunKind.Rerun, old.IsTest, old.DataSource,
            old.WindowStart, old.WindowEnd, actor?.Id, actor?.Name, deliver: deliver);
        db.ExportRuns.Add(run);
        await db.SaveChangesAsync(ct);
        return Results.Accepted($"/api/v1/exports/{d.Id}/runs", RunResponse(run));
    }

    private static async Task<IResult> Download(
        Guid runId, ScopedTenantDbContextFactory dbf, IBlobStorage blobs, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var run = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId, ct);
        if (run is not { Status: ExportRunStatus.Succeeded, BlobKey: { } key }) return Results.NotFound();
        if (run.FileDeletedAt is not null)
            return Results.Json(new { error = "This file was deleted by the retention policy — re-run its window to make it again." }, statusCode: 410);
        var stream = await blobs.OpenReadAsync(key, ct);
        if (stream is null) return Results.NotFound(new { error = "The file is no longer stored." });
        var actor = ActorResolver.Resolve(http.User);
        db.ExportAuditEntries.Add(ExportAuditEntry.Record(run.TenantId, run.DefinitionId, run.Id, ExportAuditAction.Downloaded,
            actor?.Name, run.FileName));
        await db.SaveChangesAsync(ct);
        return Results.File(stream, run.ContentType ?? "application/octet-stream", run.FileName);
    }

    // ── Schedule + delivery (session 2) ────────────────────────────────────────

    private static IResult Templates() => Results.Ok(ExportStarterTemplates.All);

    /// <summary>Saves (or clears) the schedule. Not part of the vendor-approved spec, so it doesn't mark the export
    /// changed since approval.</summary>
    private static async Task<IResult> SaveSchedule(
        Guid id, ScheduleRequest req, ScopedTenantDbContextFactory dbf,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        if (req.Schedule is { } sch && ExportScheduleCalculator.Validate(sch) is { } error) return Results.BadRequest(new { error });
        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        d.SetSchedule(req.Schedule);
        await db.SaveChangesAsync(ct);
        var summary = req.Schedule is null ? "Schedule removed" : "Schedule: " + ExportScheduleCalculator.Describe(req.Schedule, d.Spec.TimeZone);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name, summary, ct);
        return Results.Ok(ToResponse(d, null));
    }

    /// <summary>What an unsaved schedule would do — the editor's plain-English line and next run times.</summary>
    private static IResult SchedulePreview(SchedulePreviewRequest req)
    {
        if (ExportScheduleCalculator.Validate(req.Schedule) is { } error) return Results.Ok(new { error, description = (string?)null, nextRuns = new List<object>() });
        return Results.Ok(new
        {
            error = (string?)null,
            description = ExportScheduleCalculator.Describe(req.Schedule, req.DataTimeZone),
            nextRuns = NextRuns(req.Schedule, req.DataTimeZone),
        });
    }

    private static async Task<IResult> SaveTargets(
        Guid id, TargetsRequest req, ScopedTenantDbContextFactory dbf,
        [FromKeyedServices("tenant")] IVersionHistoryService versions, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        if (ActorResolver.Resolve(http.User) is not { } actor) return Results.Unauthorized();
        var targets = req.Targets ?? [];
        foreach (var t in targets)
            if (t.Validate() is { } error) return Results.BadRequest(new { error });
        if (targets.GroupBy(t => t.Name.Trim(), StringComparer.OrdinalIgnoreCase).FirstOrDefault(g => g.Count() > 1) is { } dup)
            return Results.BadRequest(new { error = $"Two delivery targets are named '{dup.Key}'." });
        if (targets.GroupBy(t => t.Id).Any(g => g.Count() > 1)) return Results.BadRequest(new { error = "Duplicate target ids." });

        await using var db = dbf.Create();
        var d = await db.ExportDefinitions.FirstOrDefaultAsync(x => x.Id == id, ct);
        if (d is null) return Results.NotFound();
        d.SetDeliveryTargets(targets.Select(t => t with { Name = t.Name.Trim() }).ToList());
        await db.SaveChangesAsync(ct);
        await versions.SnapshotAsync(VersionedEntityType.ExportDefinition, d.Id, Snapshot(d), actor.Id, actor.Name,
            "Delivery targets: " + (targets.Count == 0 ? "none" : string.Join(", ", targets.Select(t => $"{t.Name} ({t.Type}{(t.Enabled ? "" : ", off")})"))), ct);
        return Results.Ok(ToResponse(d, null));
    }

    /// <summary>Signs in to the (possibly unsaved) target and reports the fingerprint to pin. Uploads nothing.</summary>
    private static async Task<IResult> TestTarget(
        Guid id, TestTargetRequest req, IExportDeliveryService delivery, TenantContext tc, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return Results.Unauthorized();
        return Results.Ok(await delivery.TestAsync(tenant.Subdomain, req.Target, ct));
    }

    /// <summary>Sends an existing file to the chosen targets — a test file to the vendor's test folder, or a past file
    /// again. A real (non-test) file only goes out once the vendor has approved the export.</summary>
    private static async Task<IResult> Send(
        Guid runId, SendRequest req, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        var actor = ActorResolver.Resolve(http.User);
        await using var db = dbf.Create();
        var run = await db.ExportRuns.AsNoTracking().FirstOrDefaultAsync(x => x.Id == runId, ct);
        if (run is null) return Results.NotFound();
        if (run.Status != ExportRunStatus.Succeeded || run.FileDeletedAt is not null)
            return Results.Conflict(new { error = "Only a finished, still-stored file can be sent." });
        var d = await db.ExportDefinitions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == run.DefinitionId, ct);
        if (d is null) return Results.NotFound();
        if (!run.IsTest && SendBlocked(d, requireTarget: false) is { } blocked) return Results.Conflict(new { error = blocked });

        var chosen = d.DeliveryTargets.Where(t => req.TargetIds?.Contains(t.Id) == true).ToList();
        if (chosen.Count == 0) return Results.BadRequest(new { error = "Choose where to send it." });
        if (chosen.FirstOrDefault(t => !t.Enabled) is { } off) return Results.BadRequest(new { error = $"'{off.Name}' is turned off." });
        // A target already waiting to retry this file is brought forward rather than sent twice.
        var waiting = await db.ExportDeliveries
            .Where(x => x.RunId == run.Id && (x.Status == ExportDeliveryStatus.Queued || x.Status == ExportDeliveryStatus.Running))
            .ToListAsync(ct);
        foreach (var t in chosen)
        {
            var existing = waiting.FirstOrDefault(x => x.TargetId == t.Id);
            if (existing is null) db.ExportDeliveries.Add(ExportDelivery.Queue(run, t.Id, t.Name, t.Type, actor?.Name));
            else if (existing.Status == ExportDeliveryStatus.Queued) existing.Retry(actor?.Name);
        }
        db.ExportAuditEntries.Add(ExportAuditEntry.Record(run.TenantId, run.DefinitionId, run.Id, ExportAuditAction.SendRequested,
            actor?.Name, $"{run.FileName}{(run.IsTest ? " (test)" : "")} → {string.Join(", ", chosen.Select(t => t.Name))}"));
        await db.SaveChangesAsync(ct);
        return Results.Accepted();
    }

    private static async Task<IResult> RetryDelivery(
        Guid deliveryId, ScopedTenantDbContextFactory dbf, TenantContext tc, HttpContext http, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        var delivery = await db.ExportDeliveries.FirstOrDefaultAsync(x => x.Id == deliveryId, ct);
        if (delivery is null) return Results.NotFound();
        try { delivery.Retry(ActorResolver.Resolve(http.User)?.Name); }
        catch (InvalidOperationException ex) { return Results.Conflict(new { error = ex.Message }); }
        await db.SaveChangesAsync(ct);
        return Results.Accepted();
    }

    private static async Task<IResult> Activity(Guid id, ScopedTenantDbContextFactory dbf, TenantContext tc, CancellationToken ct)
    {
        if (!tc.HasTenant) return Results.Unauthorized();
        await using var db = dbf.Create();
        return Results.Ok(await db.ExportAuditEntries.AsNoTracking().Where(x => x.DefinitionId == id)
            .OrderByDescending(x => x.At).Take(200)
            .Select(x => new { x.Id, x.RunId, x.Action, x.ActorName, x.Detail, x.At }).ToListAsync(ct));
    }

    /// <summary>Why a real file can't go to the vendor yet, or null. Test files are never blocked.</summary>
    private static string? SendBlocked(ExportDefinition d, bool requireTarget = true)
    {
        if (d.Status is not (ExportStatus.Approved or ExportStatus.Live or ExportStatus.Paused))
            return "A real file can only be sent once the vendor has approved this export — send a test file instead.";
        if (requireTarget && !d.DeliveryTargets.Any(t => t.Enabled)) return "There's no delivery target to send it to.";
        return null;
    }

    private static List<object> NextRuns(ExportSchedule schedule, string dataTimeZone) =>
        ExportScheduleCalculator.Next(schedule, DateTimeOffset.UtcNow, 3).Select(at =>
        {
            var (start, end) = ExportScheduleCalculator.Window(schedule, dataTimeZone, at, null);
            return (object)new { runAt = at, windowStart = start, windowEnd = end };
        }).ToList();

    // ── Helpers ────────────────────────────────────────────────────────────────

    private static ExportSpec WithDefaults(ExportSpec spec, string? tenantTimezone) =>
        string.IsNullOrWhiteSpace(spec.TimeZone)
            ? spec with { TimeZone = string.IsNullOrWhiteSpace(tenantTimezone) ? "America/New_York" : tenantTimezone }
            : spec;

    /// <summary>[from 00:00, to + 1 day 00:00) in the export's time zone, as UTC.</summary>
    internal static bool TryWindow(DateOnly? from, DateOnly? to, string tz, out DateTimeOffset start, out DateTimeOffset end, out string? error)
    {
        start = end = default;
        error = null;
        if (from is null || to is null) { error = "Choose the dates to include."; return false; }
        if (to < from) { error = "The end date is before the start date."; return false; }
        if (to.Value.DayNumber - from.Value.DayNumber > 366) { error = "Choose at most a year."; return false; }
        var zone = ExportGenerator.ResolveZone(tz) ?? TimeZoneInfo.Utc;
        start = LocalMidnight(from.Value, zone);
        end = LocalMidnight(to.Value.AddDays(1), zone);
        return true;
    }

    private static DateTimeOffset LocalMidnight(DateOnly day, TimeZoneInfo zone)
    {
        var local = day.ToDateTime(TimeOnly.MinValue);
        return new DateTimeOffset(local, zone.GetUtcOffset(local)).ToUniversalTime();
    }

    private static string Snapshot(ExportDefinition d) => JsonSerializer.Serialize(new
    {
        d.Name, d.Description, d.Status, d.SpecRevision, d.Spec,
        Approval = d.ApprovedAt is null ? null : new { d.ApprovedAt, d.ApprovedByVendorContact, d.ApprovalRecordedByName, d.ApprovalNote, d.ApprovedRunId, d.ApprovedSpecRevision },
        d.Schedule, d.DeliveryTargets,
    }, new JsonSerializerOptions(JsonSerializerDefaults.Web));

    private static object ToResponse(ExportDefinition d, ExportRun? lastRun) => new
    {
        d.Id, d.Name, d.Description, d.Status, d.Spec, d.SpecRevision, d.ChangedSinceApproval,
        Approval = d.ApprovedAt is null ? null : new
        {
            At = d.ApprovedAt, VendorContact = d.ApprovedByVendorContact, RecordedBy = d.ApprovalRecordedByName,
            Note = d.ApprovalNote, RunId = d.ApprovedRunId, SpecRevision = d.ApprovedSpecRevision,
        },
        d.Schedule, d.DeliveryTargets, d.LastScheduledFor,
        ScheduleDescription = d.Schedule is null ? null : ExportScheduleCalculator.Describe(d.Schedule, d.Spec.TimeZone),
        NextRuns = d.Schedule is null || d.Status != ExportStatus.Live ? [] : NextRuns(d.Schedule, d.Spec.TimeZone),
        d.CreatedAt, d.UpdatedAt,
        LastRun = lastRun is null ? null : RunResponse(lastRun, []),
    };

    private static object RunResponse(ExportRun r) => RunResponse(r, []);

    private static object RunResponse(ExportRun r, IEnumerable<ExportDelivery> deliveries) => new
    {
        r.Id, r.DefinitionId, r.DefinitionName, r.SpecRevision, r.Kind, r.IsTest, r.DataSource, r.WindowStart, r.WindowEnd,
        r.Status, r.Attempts, r.Error, r.RequestedByName, r.RowCount, r.CallCount, r.FileName, r.FileSize, r.Sha256,
        r.QueuedAt, r.StartedAt, r.FinishedAt, r.ScheduledFor, r.Deliver, r.FileDeletedAt,
        Deliveries = deliveries.Select(x => new
        {
            x.Id, x.TargetId, x.TargetName, x.TargetType, x.Status, x.Attempts, x.MaxAttempts, x.NextAttemptAt, x.Error,
            x.SentAs, x.RequestedByName, x.QueuedAt, x.DeliveredAt,
        }).ToList(),
    };

    public sealed record SaveExportRequest(string Name, string? Description, ExportSpec? Spec);
    public sealed record LifecycleRequest(string Action, string? VendorContact, string? Note, Guid? RunId);
    public sealed record PreviewRequest(ExportSpec Spec, string? Name, DateOnly? From, DateOnly? To, string? DataSource, bool IsTest, int? MaxCalls);
    public sealed record PreviewResponse(bool Success, string? Error, int RowCount, int CallCount, bool Truncated, string Text, string FileName, bool Grid);
    public sealed record QueueRunRequest(DateOnly? From, DateOnly? To, bool IsTest, string? DataSource, bool Deliver = false);
    public sealed record RerunRequest(bool Deliver = false);
    public sealed record ScheduleRequest(ExportSchedule? Schedule);
    public sealed record SchedulePreviewRequest(ExportSchedule Schedule, string DataTimeZone);
    public sealed record TargetsRequest(List<ExportDeliveryTarget>? Targets);
    public sealed record TestTargetRequest(ExportDeliveryTarget Target);
    public sealed record SendRequest(List<Guid>? TargetIds);
}
