using System.Net;
using ContactConnection.Application.Interfaces.Services;
using ContactConnection.Application.Services;
using ContactConnection.Domain.Entities;
using ContactConnection.Infrastructure.Data;
using ContactConnection.Infrastructure.FlowDocs;
using Microsoft.EntityFrameworkCore;

namespace ContactConnection.Api.Endpoints;

/// <summary>
/// Flow document (S183): a client-ready PDF of a script or call flow — chart plus every step — from the Flows list.
/// Download it, or have it emailed to yourself (your own sign-in address only) to forward to a client.
/// </summary>
public static class FlowDocumentEndpoints
{
    public static IEndpointRouteBuilder MapFlowDocumentEndpoints(this IEndpointRouteBuilder app)
    {
        app.MapGet("/api/v1/flows/{id:guid}/document", Download).RequireAuthorization();
        app.MapPost("/api/v1/flows/{id:guid}/document/email", Email).RequireAuthorization();
        return app;
    }

    public record EmailDocumentRequest(string? Version);

    private static bool CanView(HttpContext http) =>
        (http.User.FindFirst("permissions")?.Value ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Any(p => p is Permission.FlowsView or Permission.FlowsManage);

    private static async Task<(IResult? Error, byte[] Pdf, string FileName, Flow Flow, Agent Me)> BuildAsync(
        Guid id, string? version, ScopedTenantDbContextFactory dbf, TenantContext tc, FlowDocumentService docs, HttpContext http, CancellationToken ct)
    {
        if (tc.Current is not { } tenant) return (Results.Unauthorized(), [], "", null!, null!);
        if (!CanView(http) || !Guid.TryParse(http.User.FindFirst("sub")?.Value, out var meId)) return (Results.Forbid(), [], "", null!, null!);
        await using var db = dbf.Create();
        var flow = await db.Flows.AsNoTracking().FirstOrDefaultAsync(f => f.Id == id, ct);
        if (flow is null) return (Results.NotFound(), [], "", null!, null!);
        var me = await db.Agents.AsNoTracking().FirstOrDefaultAsync(a => a.Id == meId, ct);
        if (me is null) return (Results.Forbid(), [], "", null!, null!);
        var draft = string.Equals(version, "draft", StringComparison.OrdinalIgnoreCase);
        if (!draft && (!flow.IsActive || flow.PublishedDefinition is null))
            return (Results.BadRequest(new { error = "This flow hasn't been published yet — choose the draft version." }), [], "", flow, me);
        var (pdf, fileName, _) = await docs.BuildAsync(db, flow, draft, tenant, $"{me.FirstName} {me.LastName}".Trim(), ct);
        return (null, pdf, fileName, flow, me);
    }

    private static async Task<IResult> Download(Guid id, string? version, ScopedTenantDbContextFactory dbf, TenantContext tc,
        FlowDocumentService docs, HttpContext http, CancellationToken ct)
    {
        var r = await BuildAsync(id, version, dbf, tc, docs, http, ct);
        return r.Error ?? Results.File(r.Pdf, "application/pdf", r.FileName);
    }

    private static async Task<IResult> Email(Guid id, EmailDocumentRequest req, ScopedTenantDbContextFactory dbf, TenantContext tc,
        FlowDocumentService docs, IEmailService email, HttpContext http, CancellationToken ct)
    {
        var r = await BuildAsync(id, req.Version, dbf, tc, docs, http, ct);
        if (r.Error is not null) return r.Error;
        var tenant = tc.Current!;
        var draft = string.Equals(req.Version, "draft", StringComparison.OrdinalIgnoreCase);
        var which = draft ? $"draft version {r.Flow.Version} (not live)" : $"published version {r.Flow.PublishedVersion}";
        var name = WebUtility.HtmlEncode(r.Flow.Name);
        await email.SendAsync(new EmailMessage
        {
            To = [r.Me.Email],
            FromName = tenant.DisplayName ?? tenant.Name,
            Subject = $"Flow document: {r.Flow.Name} ({(draft ? $"draft v{r.Flow.Version}" : $"v{r.Flow.PublishedVersion}")})",
            HtmlBody = $"""
                <div style="font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#111827">
                  <p>Hi {WebUtility.HtmlEncode(r.Me.FirstName)},</p>
                  <p>Attached is the flow document for <b>{name}</b> — {which}: a chart of the whole flow and every step's
                  script, ready to forward to your client.</p>
                  <p style="color:#6b7280;font-size:12px">Generated by ContactConnection. It shows the script as it stood when you
                  asked for it; generate a new one after changes.</p>
                </div>
                """,
            Attachments = [new EmailAttachment(r.FileName, r.Pdf, "application/pdf")],
        }, ct);
        return Results.Ok(new { sentTo = r.Me.Email });
    }
}
